/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBoxesRouteImport } from './routes/_app/boxes'
import { Route as AppCashRouteImport } from './routes/_app/cash'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppPreorderRouteImport } from './routes/_app/preorder'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppStockRouteImport } from './routes/_app/stock'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients.index'
import { Route as AppClientsClientIdRouteImport } from './routes/_app/clients.$clientId'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders.index'
import { Route as AppOrdersOrderIdRouteImport } from './routes/_app/orders.$orderId'
import { Route as AppOrdersNewRouteImport } from './routes/_app/orders.new'
import { Route as AppWorkersIndexRouteImport } from './routes/_app/workers.index'
import { Route as AppWorkersWorkerIdRouteImport } from './routes/_app/workers.$workerId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBoxesRoute = AppBoxesRouteImport.update({
  id: '/boxes',
  path: '/boxes',
  getParentRoute: () => AppRoute,
} as any)
const AppCashRoute = AppCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppPreorderRoute = AppPreorderRouteImport.update({
  id: '/preorder',
  path: '/preorder',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkersIndexRoute = AppWorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkersWorkerIdRoute = AppWorkersWorkerIdRouteImport.update({
  id: '/workers/$workerId',
  path: '/workers/$workerId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/boxes': typeof AppBoxesRoute
  '/cash': typeof AppCashRoute
  '/finance': typeof AppFinanceRoute
  '/more': typeof AppMoreRoute
  '/preorder': typeof AppPreorderRoute
  '/reports': typeof AppReportsRoute
  '/stock': typeof AppStockRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/workers/$workerId': typeof AppWorkersWorkerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/clients/': typeof AppClientsIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/workers/': typeof AppWorkersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/boxes': typeof AppBoxesRoute
  '/cash': typeof AppCashRoute
  '/finance': typeof AppFinanceRoute
  '/more': typeof AppMoreRoute
  '/preorder': typeof AppPreorderRoute
  '/reports': typeof AppReportsRoute
  '/stock': typeof AppStockRoute
  '/': typeof AppIndexRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/workers/$workerId': typeof AppWorkersWorkerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/clients': typeof AppClientsIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/workers': typeof AppWorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/boxes': typeof AppBoxesRoute
  '/_app/cash': typeof AppCashRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/preorder': typeof AppPreorderRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRoute
  '/_app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/workers/$workerId': typeof AppWorkersWorkerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/workers/': typeof AppWorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/boxes'
    | '/cash'
    | '/finance'
    | '/more'
    | '/preorder'
    | '/reports'
    | '/stock'
    | '/clients/$clientId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/workers/$workerId'
    | '/api/auth/$'
    | '/clients/'
    | '/orders/'
    | '/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/boxes'
    | '/cash'
    | '/finance'
    | '/more'
    | '/preorder'
    | '/reports'
    | '/stock'
    | '/'
    | '/clients/$clientId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/workers/$workerId'
    | '/api/auth/$'
    | '/clients'
    | '/orders'
    | '/workers'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/boxes'
    | '/_app/cash'
    | '/_app/finance'
    | '/_app/more'
    | '/_app/preorder'
    | '/_app/reports'
    | '/_app/stock'
    | '/_app/'
    | '/_app/clients/$clientId'
    | '/_app/orders/$orderId'
    | '/_app/orders/new'
    | '/_app/workers/$workerId'
    | '/api/auth/$'
    | '/_app/clients/'
    | '/_app/orders/'
    | '/_app/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boxes': {
      id: '/_app/boxes'
      path: '/boxes'
      fullPath: '/boxes'
      preLoaderRoute: typeof AppBoxesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash': {
      id: '/_app/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof AppCashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preorder': {
      id: '/_app/preorder'
      path: '/preorder'
      fullPath: '/preorder'
      preLoaderRoute: typeof AppPreorderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId': {
      id: '/_app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workers/': {
      id: '/_app/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof AppWorkersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workers/$workerId': {
      id: '/_app/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof AppWorkersWorkerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBoxesRoute: typeof AppBoxesRoute
  AppCashRoute: typeof AppCashRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppMoreRoute: typeof AppMoreRoute
  AppPreorderRoute: typeof AppPreorderRoute
  AppReportsRoute: typeof AppReportsRoute
  AppStockRoute: typeof AppStockRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppWorkersWorkerIdRoute: typeof AppWorkersWorkerIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppWorkersIndexRoute: typeof AppWorkersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBoxesRoute: AppBoxesRoute,
  AppCashRoute: AppCashRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppMoreRoute: AppMoreRoute,
  AppPreorderRoute: AppPreorderRoute,
  AppReportsRoute: AppReportsRoute,
  AppStockRoute: AppStockRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppWorkersWorkerIdRoute: AppWorkersWorkerIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppWorkersIndexRoute: AppWorkersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
